const courses = [
    {
        title: "The Complete HTML course for Beginners from zero to hero",
        header: "Learn modern HTML5 by building a stunning website for your portfolio!",
        category: ["Front End", "Full Stack", "ALL Courses"],
        hours: "3h",
        lessons: "28 Lesson",
        type: "Front End",
        description: "an HTML course provides a solid foundation for anyone looking to start building websites or pursuing a career in web development. It's often the first step in learning how to create dynamic and interactive web experiences.",
        willLearn: "Throughout this course, Abdelrahman Gamal will leverage their expertise and passion for web development to provide you with comprehensive instruction, practical insights, and hands-on exercises. By the end of the course, you'll have the knowledge and confidence to create dynamic, responsive, and visually appealing web pages using HTML.",
        requirement: { r1: "Basic computer literacy, familiarity with web browsing.", r2: "Anyone with an interest in web development can enroll." },
        instructor: "6626af5475042204c792ecb1",
    },
    {
        title: "The Complete Node Js course for Beginners from zero to hero",
        header: "Learn Node.js by building real-world applications with Node JS, Express, MongoDB, and more!",
        category: ["Back End", "Full Stack", "ALL Courses"],
        hours: "12h",
        lessons: "84 Lesson",
        type: "Back End",
        description: "Node.js has revolutionized web development by allowing JavaScript to run on the server side, enabling developers to build fast, scalable, and real-time applications. In this course, we'll take you from the basics of Node.js to advanced topics, equipping you with the knowledge and tools to build high-performance web applications with ease.",
        willLearn: "Throughout this course, Ahmed Boghdady will guide you through a comprehensive curriculum, combining theoretical concepts with hands-on exercises and real-world examples. By the end of the course, you'll have the expertise to create robust and efficient server-side applications using Node.js.",
        requirement: { r1: "Familiarity with JavaScript programming language basics is essential.", r2: "May also recommend knowledge of web development concepts like HTML, CSS, and basic understanding of backend development." },
        instructor: "6626b03c75042204c792ecb4",
    },
    {
        title: "The Complete JavaScript course from zero to hero",
        header: "Learn Javascript Today From Beginner to Advanced by Completing a Challenging Real-Life Project & Coding Exercises",
        category: ["Front End", "JavaScript", "Back End", "Full Stack", "ALL Courses",
        ],
        hours: "10h",
        lessons: "80 Lesson",
        type: "JavaScript",
        description: "JavaScript is the backbone of modern web development, empowering developers to create dynamic and interactive web applications. If you're ready to take your programming skills to the next level, Mastering JavaScript: From Fundamentals to Advanced Concepts is the perfect course for you.",
        willLearn: "Throughout this course, Abdelrahman Gamal will guide you through a comprehensive curriculum,Led by an experienced instructor proficient in JavaScript development, guiding students through the fundamentals and advanced concepts of the language.Covers a wide range of topics including variables, data types, operators, control flow, functions, arrays, objects, DOM manipulation, asynchronous JavaScript, error handling, ES6 features, and more. empowering students to pursue careers as front-end developers, full-stack developers, or JavaScript engineers.",
        requirement: { r1: "Basic understanding of HTML and CSS fundamentals.", r2: "Familiarity with programming concepts such as variables, data types, conditionals, loops, and functions can also be helpful." },
        willLearn: "Throughout this course, Abdelrahman Gamal will guide you through a comprehensive curriculum,Led by an experienced instructor proficient in JavaScript development, guiding students through the fundamentals and advanced concepts of the language.Covers a wide range of topics including variables, data types, operators, control flow, functions, arrays, objects, DOM manipulation, asynchronous JavaScript, error handling, ES6 features, and more. empowering students to pursue careers as front-end developers, full-stack developers, or JavaScript engineers.",
        requirement: { r1: "Basic understanding of HTML and CSS fundamentals.", r2: "Familiarity with programming concepts such as variables, data types, conditionals, loops, and functions can also be helpful." },
        instructor: "6626af5475042204c792ecb1",
    },
    {
        title: "The Complete Bootstrap course for Beginners",
        header: "Learn to customize and build modern websites from scratch using Bootstrap 5",
        category: ["Front End", "ALL Courses"],
        hours: "3h",
        lessons: "26 Lessons",
        type: "Front End",
        description: "In today's digital landscape, creating responsive and visually appealing websites is essential for success. Enter Bootstrap - the world's most popular front-end framework for building responsive, mobile-first web projects with ease. If you're ready to elevate your web design skills and create stunning websites that look great on any device, Mastering Bootstrap: Building Responsive and Stunning Websites is the course for you.",
        willLearn: "Throughout this course, Abdelrahman Gamal will guide you through a comprehensive curriculum,  Led by an experienced instructor proficient in Bootstrap development, guiding students through the fundamentals and advanced concepts of building responsive",
        requirement: { r1: "Basic understanding of HTML and CSS fundamentals.", r2: "Familiarity with web development concepts such as grids, typography, and layouts can be beneficial." },
        instructor: "6626af5475042204c792ecb1",
    },
    {
        title: "The Complete React Js course for Beginners from zero to hero",
        header: "Dive in and learn React.js from scratch! Learn React, Hooks, Redux, React Router, Best Practices and way more!",
        category: ["Front End", "Full Stack", "ALL Courses"],
        hours: "10h 20m",
        lessons: "110 Lesson",
        type: "React Js",
        description: "your comprehensive guide to mastering one of the most popular JavaScript libraries for building user interfaces. React has revolutionized front-end development by providing a component-based architecture that makes it easy to create reusable and scalable UI components.",
        willLearn: "Throughout this course, Mahmoud Bakr will guide you through a comprehensive curriculum, Led by an experienced instructor proficient in React development, guiding students through the fundamentals and advanced concepts of building web applications with React.Focuses on developing practical skills and knowledge that are directly applicable in real-world web development projects using React.js, preparing students for success in React development roles.",
        requirement: { r1: "Need solid understanding of HTML, CSS, and JavaScript fundamentals.", r2: "Familiarity with ES6 features such as arrow functions, classes, and modules is also beneficial. " },
        instructor: "6626b34575042204c792ecc6",
    },
    {
        title: "The Complete Nest Js course for Beginners from zero to hero",
        header: "Develop and deploy enterprise back-end applications following best practices using Node.js and TypeScript",
        category: ["Back End", "Full Stack", "ALL Courses"],
        hours: "22h",
        lessons: "142 Lesson",
        type: "Nest Js Course",
        description: "Nest Js empowers developers to build fast, scalable, and SEO-friendly web applications with ease, combining the simplicity of React with the power of server-side rendering.  Next.js uses a file-based routing system that simplifies navigation in your application.",
        willLearn: "Throughout this course, Ahmed Boghdady will guide you through a comprehensive curriculum, Led by an experienced instructor proficient in Next.js development, guiding students through the fundamentals and advanced concepts of building modern web applications with Next.js.Covers a wide range of topics including server-side rendering (SSR), static site generation (SSG), data fetching, routing, API routes, deployment, and performance optimization.",
        requirement: { r1: "Need a solid understanding of JavaScript or TypeScript.", r2: "Familiarity with Node.js and Express.js can be beneficial." },
        instructor: "6626b03c75042204c792ecb4"
    },
    {
        title: "The Complete CSS course for Beginners from zero to hero",
        header: "Learn CSS for the first time or brush up your CSS skills and dive in even deeper. EVERY web developer has to know CSS. (incl. Flexbox, Grid )",
        category: ["Front End", "Full Stack", "ALL Courses"],
        hours: "8h",
        lessons: "52 Lesson",
        type: "Front End",
        description: "In this comprehensive course, we'll take you from the basics of CSS to advanced techniques, equipping you with the knowledge and skills to create beautiful, responsive, and accessible web designs. Whether you're a beginner or an experienced developer, this course will empower you to leverage the full potential of CSS and elevate your web development skills to new heights.",
        willLearn: "Throughout this course, Osama Elzero will share their wealth of knowledge and practical insights, empowering you to create visually stunning, responsive, and user-friendly websites. From mastering the fundamentals to exploring advanced techniques, you'll gain the confidence and skills needed to tackle any design challenge with ease.",
        requirement: { r1: "Basic understanding of HTML.", r2: "Familiarity with web browsers and web development concepts is also helpful." },
        instructor: "6626b27675042204c792ecb7",
    },
    {
        title: "The Complete CS50 course form Scratch for Beginners",
        header: "CS50 is an introductory computer science course that covers fundamental concepts, problem-solving skills, and programming languages, designed to provide students with a strong foundation in computer science.",
        category: ["CS50", "ALL Courses"],
        hours: "10h",
        lessons: "82 Lesson",
        type: "CS50",
        description: "Developed by Harvard University, CS50 is renowned for its rigorous curriculum, engaging lectures, and hands-on projects that challenge students to think critically and creatively. Through a blend of lectures, problem sets, and programming assignments, you'll explore fundamental concepts in computer science and gain practical skills that are applicable across various domains and industries.",
        willLearn: "Throughout this course, Abdelrahman Gamal will guide you through a comprehensive curriculum, The instructor possesses expertise in computer science concepts, programming languages, algorithms, data structures, and other fundamental topics covered in the CS50 curriculum.Demonstrates a passion for teaching and a commitment to helping students succeed in learning computer science concepts, regardless of their prior experience or background.",
        requirement: { r1: "Having basic computer literacy and problem-solving skills can be beneficial.", r2: "familiarity with concepts in mathematics, logic, and critical thinking can also aid in understanding the material covered in CS50." },
        instructor: "6626af5475042204c792ecb1",
    },
    {
        title: "CCNP Security (SCOR 350-701) ",
        header: "Implementing and Operating Cisco Security Core Technologies (SCOR 350-701) with Step by Step Lab Workbook",
        category: ["Network", "Security", "ALL Courses"],
        hours: "10h",
        lessons: "54 Lesson",
        type: "CCNP Security",
        description: "Welcome to the CCNP Security (SCOR 350-701) Course: Securing Networks with Cisco Technologies, your gateway to becoming a certified Cisco security professional and mastering the latest technologies and techniques for securing modern networks. Developed by Cisco, the CCNP Security certification validates your expertise in designing, implementing, and managing security solutions using Cisco technologies.",
        willLearn: "Throughout this course, Abeer Hosni will guide you through a comprehensive curriculum,  Led by a Cisco Certified Instructor (CCI) or a seasoned networking professional with expertise in Cisco technologies, guiding students through the CCNP certification journey.Covers a wide range of topics including advanced routing protocols (OSPF, EIGRP, BGP), switching technologies (VLANs, STP, EtherChannel), network security, QoS (Quality of Service), MPLS (Multiprotocol Label Switching), and more.",
        requirement: { r1: "Basic understanding of networking concepts: including knowledge of TCP/IP, OSI model, subnetting, routing, switching, and VLANs.", r2: "Cisco Certified Network Associate (CCNA) certification or equivalent knowledge." },
        instructor: "6626b30575042204c792ecbd",
    },
    {
        title: "The Complete CCNA 200-301 course",
        header: "Everything you need to pass the Cisco CCNA 200-301 Exam - a complete course with IT Lab.",
        category: ["Network", "Security", "ALL Courses"],
        hours: "37h",
        lessons: "52 Lesson",
        type: "CCNA Security",
        description: "Welcome to the CCNA 200-301 Certification Course, your comprehensive guide to mastering the fundamentals of networking and preparing for the Cisco Certified Network Associate (CCNA) exam. Whether you're a beginner in the field of networking or an experienced professional looking to enhance your skills, this course is designed to provide you with the knowledge and practical experience needed to succeed in the dynamic world of IT networking.",
        willLearn: "Throughout this course, Mahmoud Miaari will guide you through a comprehensive curriculum,Led by a Cisco Certified Instructor (CCI) or a seasoned networking professional with expertise in Cisco technologies, guiding students through the CCNA certification journey.Covers a wide range of topics including networking basics, TCP/IP, subnetting, VLANs, routing protocols (e.g., OSPF, EIGRP), WAN technologies, network security, and network automation.",
        requirement: { r1: "Basic understanding of networking concepts: including knowledge of TCP/IP, OSI model, subnetting, routing, switching, and VLANs.", r2: "Familiarity with basic networking technologies: Prior knowledge of Ethernet, IP addressing, and common networking devices like routers and switches is beneficial." },
        instructor: "6626b31675042204c792ecc0",
    },
    {
        title: "AWS Cloud Practitioner Essentials",
        header: "Learn Cloud Computing Concepts and AWS Basics | Master AWS Fundamentals and Hands-on Skills on Amazon Web Services (AWS).",
        category: ["AWS", "ALL Courses"],
        hours: "7h",
        lessons: "58 Lesson",
        type: "AWS Cloud",
        description: "This course is designed to provide you with a solid foundation in AWS cloud computing concepts, services, and best practices, empowering you to leverage the full potential of AWS to drive innovation and growth in your organization. Whether you're a beginner or an experienced IT professional, this course will equip you with the knowledge and skills to navigate the AWS cloud with confidence and efficiency.",
        willLearn: "Throughout this course, Saleh Saad will guide you through a comprehensive curriculum, Led by an AWS Certified Instructor who has demonstrated expertise in AWS technologies and best practices, guiding students through the AWS cloud learning journey.Covers cloud architecture principles, best practices, and design patterns for building scalable, resilient, and cost-effective solutions on AWS.",
        requirement: { r1: "Basic understanding of cloud computing concepts: Familiarity with the fundamentals of cloud computing, including concepts such as Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS), is beneficial.", r2: "Basic knowledge of IT concepts: Some understanding of networking, storage, virtualization, and security concepts is helpful for grasping the material covered in AWS cloud courses." },
        instructor: "6626b33375042204c792ecc3",
    },
    {
        title: "Computing & Security Essentials",
        header: "A course describing the basics of computing and Security Essentials and most of the aspects related to this topic (incl. Virtualization Technology, Networks OSI Model & Networks Protocols) ",
        category: ["Security", "ALL Courses"],
        hours: "9h",
        lessons: "15 Lesson",
        type: "Computing & Security",
        description: "This course is designed to provide you with a solid foundation in both computing concepts and security principles, empowering you to navigate the complexities of the digital world with confidence. Whether you're a beginner or an experienced professional, this course will equip you with the knowledge and skills to protect yourself and your organization from cyber threats and ensure the confidentiality, integrity, and availability of information.",
        willLearn: "Throughout this course, Mostafa Abd ElSalam will guide you through a comprehensive curriculum, The instructor possesses expertise in information security concepts, principles, and practices, including foundational knowledge in computing and cybersecurity essentials.Explores various security controls and mechanisms used to protect information systems and data, including access controls, network security measures, encryption techniques, intrusion detection and prevention systems (IDPS), and incident response procedures.Discusses risk management principles and methodologies, including risk assessment, risk analysis, risk treatment strategies, and the role of risk management in cybersecurity decision-making.",
        requirement: { r1: "Basic computer literacy, familiarity with web browsing.", r2: "Anyone with an interest in web development can enroll." },
        instructor: "6626b29e75042204c792ecba",
    }
];

const instructors = [
    {
        "name": "Abdelrahman Gamal",
        "email": "abdelrahmanGamal@gmail.com",
        "password": "123456S$s",
        "title": "Full Stack Instructor and Web Development Expert",
        "about": "I'm a fornt-end web developer and designer with a passion for building beautiful web interfaces from scratch. ",
    },
    {

        "name": "Ahmed Boghdady",
        "email": "ahmedBoghdady@gmail.com",
        "password": "123456S$s",
        "title": "Back End Instructor and Web Development Expert",
        "about": " I am highly skilled web developer and educator specializing in Nest.js and backend development.With 7 years of experience in the industry. ",
    },
    {

        "name": "Osama Elzero",
        "email": "elzero@gmail.com",
        "password": "123456S$s",
        "title": "Front End Instructor and Web Development Expert",
        "about": "I'm a fornt-end web developer and designer with a passion for building beautiful web interfaces from scratch. ",
    },
    {

        "name": "Mostafa Abd ElSalam",
        "email": "mostafaAbdElSalam@gmail.com",
        "password": "123456S$s",
        "title": "Security Instructor and Network IT infrastructure Expert",
        "about": "I am a cybersecurity professional and educator specializing in Information Network and Security. ",
    },
    {

        "name": "Abeer Hosni",
        "email": "abeerHosni@gmail.com",
        "password": "123456S$s",
        "title": "CCNP Instructor and Network and IT infrastructure Expert",
        "about": "I am highly skilled network engineer and Cisco Certified Internetwork Expert (CCIE) specializing in Cisco networking technologies. ",
    },
    {

        "name": "Mahmoud Miaari",
        "email": "mahmoudMiaari@gmail.com",
        "password": "123456S$s",
        "title": "CCNA Instructor and Network and IT infrastructure Expert",
        "about": "I am highly skilled network engineer and Cisco Certified Internetwork Expert (CCIE) specializing in Cisco networking technologies.",
    },
    {

        "name": "Saleh Saad",
        "email": "salehSaad@gmail.com",
        "password": "123456S$s",
        "title": "AWS Cloud Instructor and AWS services Expert",
        "about": "I am highly skilled cloud architect and AWS Certified Solutions Architect specializing in Amazon Web Services (AWS).",
    },
    {

        "name": "Mahmoud Bakr",
        "email": "mahmoudBakr@gmail.com",
        "password": "123456S$s",
        "title": "Front End Instructor and Web Development Expert",
        "about": "I am highly skilled web developer and educator specializing in React.js and front-end web development. With a passion for creating interactive and dynamic user interfaces, ",
    },
];



module.exports = {
    courses,
    instructors
};